---
collections:
 - name: ansible.posix
   source: http://192.168.144.60/api/galaxy/content/rh-certified/
 - name: geerlingguy.php_roles
   source: http://192.168.144.60/api/galaxy/content/community/


